/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: cef11f5a3a917a6880f3f9d0a207de42)
interface __BaseEnv_Env {
	WHITEBOARD_CODES: KVNamespace;
	WHITEBOARD_ASSETS: R2Bucket;
	WHITEBOARD_LIBRARY: D1Database;
	NOTIFICATIONS: D1Database;
	FORM_SUBMISSION_LIMITER: RateLimit;
	WHITEBOARD_CONNECT_LIMITER: RateLimit;
	WHITEBOARD_BOARD_CONNECT_LIMITER: RateLimit;
	ASSETS: Fetcher;
	CLERK_SECRET_KEY: string;
	WHITEBOARD_ADMIN_SECRET: string;
	PUBLIC_CLERK_PUBLISHABLE_KEY: string;
	PUBLIC_CLERK_ALLOWED_DOMAINS: string;
	PUBLIC_TURNSTILE_SITEKEY: string;
	TURNSTILE_SECRET: string;
	N8N_WEBHOOK_BASE_URL: string;
	N8N_WEBHOOK_SECRET: string;
	WHITEBOARDS: DurableObjectNamespace<import("./src/worker").WhiteboardBoard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "WhiteboardBoard";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLERK_SECRET_KEY" | "WHITEBOARD_ADMIN_SECRET" | "PUBLIC_CLERK_PUBLISHABLE_KEY" | "PUBLIC_CLERK_ALLOWED_DOMAINS" | "PUBLIC_TURNSTILE_SITEKEY" | "TURNSTILE_SECRET" | "N8N_WEBHOOK_BASE_URL" | "N8N_WEBHOOK_SECRET">> {}
}
