/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 1bb876ab0e5fd87403980d6599156bff)
interface __BaseEnv_Env {
	WHITEBOARD_CODES: KVNamespace;
	WHITEBOARD_ASSETS: R2Bucket;
	WHITEBOARD_LIBRARY: D1Database;
	NOTIFICATIONS: D1Database;
	WHITEBOARD_CONNECT_LIMITER: RateLimit;
	ASSETS: Fetcher;
	CLERK_SECRET_KEY: string;
	WHITEBOARD_ADMIN_SECRET: string;
	PUBLIC_CLERK_PUBLISHABLE_KEY: string;
	PUBLIC_CLERK_ALLOWED_DOMAINS: string;
	WHITEBOARDS: DurableObjectNamespace<import("./src/worker").WhiteboardBoard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "WhiteboardBoard";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLERK_SECRET_KEY" | "WHITEBOARD_ADMIN_SECRET" | "PUBLIC_CLERK_PUBLISHABLE_KEY" | "PUBLIC_CLERK_ALLOWED_DOMAINS">> {}
}
